package gawky.processor;

public interface BaseObjectI 
{
	public void setClientid(String clientid);
	public String getClientid();
	public void setDebtor_account(String debtor_account);
	public String getDebtor_account();
	public void setRef_nr(String ref_nr);
	public String getRef_nr();
	public void setBookdate(String bookdate);
	public String getBookdate();
	public void setBookcode(String bookcode);
	public String getBookcode();
	public void setBooksubcode(String booksubcode);
	public String getBooksubcode();
	public void setBooknumber(String booknumber);
	public String getBooknumber();
	public void setCurrency(String currency);
	public String getCurrency();
	public void setAmount(String amount);
	public String getAmount();
	public void setCurrency_org(String currency_org);
	public String getCurrency_org();
	public void setAmount_org(String amount_org);
	public String getAmount_org();
	public void setDc(String dc);
	public String getDc();
	public void setCcnumber(String ccnumber);
	public String getCcnumber();
	public void setCcexpiry(String ccnumber);
	public String getCcexpiry();
	public void setAddressvalcode(String ccexpiry);
	public String getAddressvalcode();
	public void setAuthcode(String authcode);
	public String getAuthcode();
	public void setAuthdate(String authdate);
	public String getAuthdate();
	public void setCcid(String ccid);
	public String getCcid();
	public void setBanksortcode(String banksortcode);
	public String getBanksortcode();
	public void setBankaccount(String bankaccount);
	public String getBankaccount();
	public void setLastname(String lastname);
	public String getLastname();
	public void setFirstname(String firstname);
	public String getFirstname();
	public void setStreet(String street);
	public String getStreet();
	public void setZip(String zip);
	public String getZip();
	public void setCity(String city);
	public String getCity();
	public void setCountrycode(String countrycode);
	public String getCountrycode();
	public void setCountryname(String countryname);
	public String getCountryname();
	public void setBookingtext(String bookingtext);
	public String getBookingtext();
	public void setCctype(String cctype);
	public String getCctype();
	public void setPaymenttype(String paymenttype);
	public String getPaymenttype();
	public void setBanknumber(String banknumber);
	public String getBanknumber();
	public void setAuthcodelong(String authcodelong);
	public String getAuthcodelong();
	public void setRibcode(String ribcode);
	public String getRibcode();
	public void setReferencetext(String referencetext);
	public String getReferencetext();
	public void setIban(String iban);
	public String getIban();
	public void setBic(String bic);
	public String getBic();
	public void setMandate_status(String mandante_status);
	public String getMandate_status();
	public void setState(String state);
	public String getState();
	public void setMandate_id(String mandate_id);
	public String getMandate_id();
	public void setStreet2(String street2);
	public String getStreet2();
	public void setPaymenttype2(String paymenttype2);
	public String getPaymenttype2();
	public void setCompanyname(String companyname);
	public String getCompanyname();
	public void setAccountnowner(String accountowner);
	public String getAccountnowner();
	public void setAuthtime(String authtime);
	public String getAuthtime();
}
